# Generated by Django 3.2.7 on 2021-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='hood',
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
